name: Build asset clean-up app

on: 
  push:
    branches:
      - master
      - develop
jobs:
  build-repo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Temporarily save jar artifact
        uses: actions/upload-artifact@v2
        with:
          name: temp-artifact
          path: ${{ github.workspace }}/target/*.jar
          retention-days: 1
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        with:
          name: temp-artifact
          path: target/
      - name: Build Container image
        run: docker build -t ramkhot/testrepo/hello-world:1.0 .
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish Docker image
        run: docker push ramkhot/testrepo/hello-world:1.0
