name: Build asset clean-up app

on: 
  push:
     branches:
       -release 

jobs:
  build-repo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Temporarily save jar artifact
        uses: actions/upload-artifact@v2
        with:
          name: temp-artifact
          path: ${{ github.workspace }}/target/*.jar
          retention-days: 1
		
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        with:
          name: temp-artifact
          path: target/
      
      - name: Build Container image
        run: docker build -t ${{ secrets.DOCKER_REPO }}:latest .
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish Docker image
        run: docker push ${{ secrets.DOCKER_REPO }}
